{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-jcl",
    "version": "6.1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-jcl-6.1.6.jar",
          "url": "spring-jcl-6.1.6.jar",
          "size": 24539,
          "sha512": "ae26ff2bdbb1928eb4349a3b0375376c64ba1e528006f826cf37b92af1552532cf5efaa49a115665dd2e426ea3cb2ee12e7120615766c41c2c7aab9f510240dc",
          "sha256": "bfbd972fbd94dfb40cc2b19de21b769e8157497cf55555523a0e01b468b8e9b8",
          "sha1": "84cb19b30b22feca73c2ac005ca849c5890935a3",
          "md5": "acf8ba19c939bace96969efc2c5a6c2b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-jcl-6.1.6.jar",
          "url": "spring-jcl-6.1.6.jar",
          "size": 24539,
          "sha512": "ae26ff2bdbb1928eb4349a3b0375376c64ba1e528006f826cf37b92af1552532cf5efaa49a115665dd2e426ea3cb2ee12e7120615766c41c2c7aab9f510240dc",
          "sha256": "bfbd972fbd94dfb40cc2b19de21b769e8157497cf55555523a0e01b468b8e9b8",
          "sha1": "84cb19b30b22feca73c2ac005ca849c5890935a3",
          "md5": "acf8ba19c939bace96969efc2c5a6c2b"
        }
      ]
    }
  ]
}
