{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-gradle-plugin",
    "version": "3.2.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-gradle-plugin-3.2.5.jar",
          "url": "spring-boot-gradle-plugin-3.2.5.jar",
          "size": 144676,
          "sha512": "a37343f150726c45411098d8ab4f880e754cae0b4faf13d378847cf1832139f83c4e294800f18e08ee68369528fe2cab2a68f418f9f2a323252557a5d50589b7",
          "sha256": "56c065b050a441a2adb33662be1b7a943ff905a11bbadf269c0296851de4704b",
          "sha1": "1103efa22d9bc2e36ff916b58b1fb40b0a932fea",
          "md5": "7cc0056d2bc0e2ad587d15ca1b3112a3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-buildpack-platform",
          "version": {
            "requires": "3.2.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-loader-tools",
          "version": {
            "requires": "3.2.5"
          }
        },
        {
          "group": "io.spring.gradle",
          "module": "dependency-management-plugin",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.21"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-gradle-plugin-3.2.5.jar",
          "url": "spring-boot-gradle-plugin-3.2.5.jar",
          "size": 144676,
          "sha512": "a37343f150726c45411098d8ab4f880e754cae0b4faf13d378847cf1832139f83c4e294800f18e08ee68369528fe2cab2a68f418f9f2a323252557a5d50589b7",
          "sha256": "56c065b050a441a2adb33662be1b7a943ff905a11bbadf269c0296851de4704b",
          "sha1": "1103efa22d9bc2e36ff916b58b1fb40b0a932fea",
          "md5": "7cc0056d2bc0e2ad587d15ca1b3112a3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-gradle-plugin-3.2.5-javadoc.jar",
          "url": "spring-boot-gradle-plugin-3.2.5-javadoc.jar",
          "size": 319451,
          "sha512": "c4227c3f7ff176b640784e29766bd406bcbddb25cc8b94dc851117c0c9116342bad451e1b4cbd7a9e098ab03f6f96d9b8ddb2db0c3a7c542948e97972411cae0",
          "sha256": "7f15f93401e657e79e4d4e55983713f0a8444955042679d0fdc48f33a6bcb670",
          "sha1": "9d58fe6e56e74c74598e22bab2d5bf69a94e20c2",
          "md5": "ba72008117c9a40b0dab29b0c0818a75"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-gradle-plugin-3.2.5-sources.jar",
          "url": "spring-boot-gradle-plugin-3.2.5-sources.jar",
          "size": 81878,
          "sha512": "ad1b245f3d4fbf3c930aa280d6f135e14aa6b245fe66790793051e0f3fbe3a476573f41a666c60bdae046e17a02f60ac1dd9d68551484cadaf9c4ee1f051e5b0",
          "sha256": "42836524ef74726004004f684f7d9b0b55a6704309505adc01b84580a1c9e0e6",
          "sha1": "2121f55f06d89e90980952bd80d2c0b7f34116f8",
          "md5": "e27c220d1dca9b47b9a007925051af92"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-gradle-plugin-3.2.5.jar",
          "url": "spring-boot-gradle-plugin-3.2.5.jar",
          "size": 144676,
          "sha512": "a37343f150726c45411098d8ab4f880e754cae0b4faf13d378847cf1832139f83c4e294800f18e08ee68369528fe2cab2a68f418f9f2a323252557a5d50589b7",
          "sha256": "56c065b050a441a2adb33662be1b7a943ff905a11bbadf269c0296851de4704b",
          "sha1": "1103efa22d9bc2e36ff916b58b1fb40b0a932fea",
          "md5": "7cc0056d2bc0e2ad587d15ca1b3112a3"
        },
        {
          "name": "spring-boot-gradle-plugin-3.2.5.jar",
          "url": "spring-boot-gradle-plugin-3.2.5.jar",
          "size": 144676,
          "sha512": "a37343f150726c45411098d8ab4f880e754cae0b4faf13d378847cf1832139f83c4e294800f18e08ee68369528fe2cab2a68f418f9f2a323252557a5d50589b7",
          "sha256": "56c065b050a441a2adb33662be1b7a943ff905a11bbadf269c0296851de4704b",
          "sha1": "1103efa22d9bc2e36ff916b58b1fb40b0a932fea",
          "md5": "7cc0056d2bc0e2ad587d15ca1b3112a3"
        },
        {
          "name": "spring-boot-gradle-plugin-3.2.5.jar",
          "url": "spring-boot-gradle-plugin-3.2.5.jar",
          "size": 144676,
          "sha512": "a37343f150726c45411098d8ab4f880e754cae0b4faf13d378847cf1832139f83c4e294800f18e08ee68369528fe2cab2a68f418f9f2a323252557a5d50589b7",
          "sha256": "56c065b050a441a2adb33662be1b7a943ff905a11bbadf269c0296851de4704b",
          "sha1": "1103efa22d9bc2e36ff916b58b1fb40b0a932fea",
          "md5": "7cc0056d2bc0e2ad587d15ca1b3112a3"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-gradle-plugin-maven-optional",
          "version": "3.2.5"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-gradle-plugin-3.2.5.jar",
          "url": "spring-boot-gradle-plugin-3.2.5.jar",
          "size": 144676,
          "sha512": "a37343f150726c45411098d8ab4f880e754cae0b4faf13d378847cf1832139f83c4e294800f18e08ee68369528fe2cab2a68f418f9f2a323252557a5d50589b7",
          "sha256": "56c065b050a441a2adb33662be1b7a943ff905a11bbadf269c0296851de4704b",
          "sha1": "1103efa22d9bc2e36ff916b58b1fb40b0a932fea",
          "md5": "7cc0056d2bc0e2ad587d15ca1b3112a3"
        },
        {
          "name": "spring-boot-gradle-plugin-3.2.5.jar",
          "url": "spring-boot-gradle-plugin-3.2.5.jar",
          "size": 144676,
          "sha512": "a37343f150726c45411098d8ab4f880e754cae0b4faf13d378847cf1832139f83c4e294800f18e08ee68369528fe2cab2a68f418f9f2a323252557a5d50589b7",
          "sha256": "56c065b050a441a2adb33662be1b7a943ff905a11bbadf269c0296851de4704b",
          "sha1": "1103efa22d9bc2e36ff916b58b1fb40b0a932fea",
          "md5": "7cc0056d2bc0e2ad587d15ca1b3112a3"
        },
        {
          "name": "spring-boot-gradle-plugin-3.2.5.jar",
          "url": "spring-boot-gradle-plugin-3.2.5.jar",
          "size": 144676,
          "sha512": "a37343f150726c45411098d8ab4f880e754cae0b4faf13d378847cf1832139f83c4e294800f18e08ee68369528fe2cab2a68f418f9f2a323252557a5d50589b7",
          "sha256": "56c065b050a441a2adb33662be1b7a943ff905a11bbadf269c0296851de4704b",
          "sha1": "1103efa22d9bc2e36ff916b58b1fb40b0a932fea",
          "md5": "7cc0056d2bc0e2ad587d15ca1b3112a3"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-gradle-plugin-maven-optional",
          "version": "3.2.5"
        }
      ]
    }
  ]
}
