{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-orm",
    "version": "6.1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-jdbc",
          "version": {
            "requires": "6.1.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "6.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-orm-6.1.6.jar",
          "url": "spring-orm-6.1.6.jar",
          "size": 237250,
          "sha512": "e4a07b1473eeb854f69427690f24823df15d136a193af756d7b99045e787cb9c457e2c921e61d43e6b07c832eaffce8c3de632647083e9740c1b7b952b000ced",
          "sha256": "51b73cfd789756ac991dd0282f94d11c88dd90d551696830d8f568d6cb99a9e1",
          "sha1": "c8687b15d3ae95769cef73626e62ffc7fff7e0bf",
          "md5": "a8202ae1260e2d8f1006fd0e3236f21f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-jdbc",
          "version": {
            "requires": "6.1.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "6.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-orm-6.1.6.jar",
          "url": "spring-orm-6.1.6.jar",
          "size": 237250,
          "sha512": "e4a07b1473eeb854f69427690f24823df15d136a193af756d7b99045e787cb9c457e2c921e61d43e6b07c832eaffce8c3de632647083e9740c1b7b952b000ced",
          "sha256": "51b73cfd789756ac991dd0282f94d11c88dd90d551696830d8f568d6cb99a9e1",
          "sha1": "c8687b15d3ae95769cef73626e62ffc7fff7e0bf",
          "md5": "a8202ae1260e2d8f1006fd0e3236f21f"
        }
      ]
    }
  ]
}
