{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-web",
    "version": "3.2.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.2.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-json",
          "version": {
            "requires": "3.2.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-tomcat",
          "version": {
            "requires": "3.2.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.1.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-webmvc",
          "version": {
            "requires": "6.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-web-3.2.5.jar",
          "url": "spring-boot-starter-web-3.2.5.jar",
          "size": 4804,
          "sha512": "89746370105716d442eb95fe88d63d67b1595c0e6826c5cef3f8d574b7d942cc7227e964ab79a94fffb01c987dbe7118e88708768efc828dd716fe8f482f3824",
          "sha256": "aea28701aa7b644a122121337a03c947cdc038cce44f91e6d2bc3d65bc71f383",
          "sha1": "664d75553c6af42122d4db645f4924a95084e382",
          "md5": "3599bbfb968050ac82e9a2e4e93fce80"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.2.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-json",
          "version": {
            "requires": "3.2.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-tomcat",
          "version": {
            "requires": "3.2.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.1.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-webmvc",
          "version": {
            "requires": "6.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-web-3.2.5.jar",
          "url": "spring-boot-starter-web-3.2.5.jar",
          "size": 4804,
          "sha512": "89746370105716d442eb95fe88d63d67b1595c0e6826c5cef3f8d574b7d942cc7227e964ab79a94fffb01c987dbe7118e88708768efc828dd716fe8f482f3824",
          "sha256": "aea28701aa7b644a122121337a03c947cdc038cce44f91e6d2bc3d65bc71f383",
          "sha1": "664d75553c6af42122d4db645f4924a95084e382",
          "md5": "3599bbfb968050ac82e9a2e4e93fce80"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-web-3.2.5.jar",
          "url": "spring-boot-starter-web-3.2.5.jar",
          "size": 4804,
          "sha512": "89746370105716d442eb95fe88d63d67b1595c0e6826c5cef3f8d574b7d942cc7227e964ab79a94fffb01c987dbe7118e88708768efc828dd716fe8f482f3824",
          "sha256": "aea28701aa7b644a122121337a03c947cdc038cce44f91e6d2bc3d65bc71f383",
          "sha1": "664d75553c6af42122d4db645f4924a95084e382",
          "md5": "3599bbfb968050ac82e9a2e4e93fce80"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-web-maven-optional",
          "version": "3.2.5"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-web-3.2.5.jar",
          "url": "spring-boot-starter-web-3.2.5.jar",
          "size": 4804,
          "sha512": "89746370105716d442eb95fe88d63d67b1595c0e6826c5cef3f8d574b7d942cc7227e964ab79a94fffb01c987dbe7118e88708768efc828dd716fe8f482f3824",
          "sha256": "aea28701aa7b644a122121337a03c947cdc038cce44f91e6d2bc3d65bc71f383",
          "sha1": "664d75553c6af42122d4db645f4924a95084e382",
          "md5": "3599bbfb968050ac82e9a2e4e93fce80"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-web-maven-optional",
          "version": "3.2.5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-web-3.2.5-javadoc.jar",
          "url": "spring-boot-starter-web-3.2.5-javadoc.jar",
          "size": 4742,
          "sha512": "20f6c4387413fe484f5de43b912212148ef99756466d0adc4827219a7c24197fc21be5f3fa5d1a9439b5243b3f8f0a8e850c8b354a6c43d772ea614e5db359af",
          "sha256": "2d620b4582cd21e01ca85215c17f8f9fdc2d62dc028a48636ea4257a056914a0",
          "sha1": "64ce53dbbe92a1758b12c2b3183abcdebbb252d1",
          "md5": "78bd9a04d8e396c9a3f9fa4a7ca05ba6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-web-3.2.5-sources.jar",
          "url": "spring-boot-starter-web-3.2.5-sources.jar",
          "size": 4740,
          "sha512": "b70c045b4b5be7c854ab70f3eaaca1283c224837ca9a42886a105b6d24a0fb98a44498b50b1787b3abf314256d14ebe05c444ec21c9fd0fb47c6bfd5ff9237ed",
          "sha256": "588e26d366e05c3db56f08a5817323f6b1659231ddf3691c215fb89518527495",
          "sha1": "9b92aefad357e5ef62c11ed3e23e0daa81e5fa39",
          "md5": "3c658c300d944ea01b1aeefc25157cd8"
        }
      ]
    }
  ]
}
