plugins {
    id 'org.springframework.boot' apply false
    id 'io.spring.dependency-management' apply false
}

allprojects {
    group = 'com.github.thejavalistener'
    version = '0.1.0'

    repositories {
        mavenCentral()
    }
}

subprojects {
    tasks.withType(JavaCompile) {
        options.encoding = 'UTF-8'
    }
}
