{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-core",
    "version": "6.1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-jcl",
          "version": {
            "requires": "6.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-core-6.1.6.jar",
          "url": "spring-core-6.1.6.jar",
          "size": 1880852,
          "sha512": "893d9c5956c3005717dc7f09b31908dfed3588f9c81fb6180781ca687f305157cf3481f246d1a493fa348991d41a660b54e5db7ff5a4e4676570062b8c22b38b",
          "sha256": "caf51f3d51c5d95e931f411027688f1dde3986d5f2aad67ff1096ddddac36ac5",
          "sha1": "dea4b8e110b7b54a02a4907e32dbb0adee8a7168",
          "md5": "852be6055a31d2ce17b5d231b17f732e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-jcl",
          "version": {
            "requires": "6.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-core-6.1.6.jar",
          "url": "spring-core-6.1.6.jar",
          "size": 1880852,
          "sha512": "893d9c5956c3005717dc7f09b31908dfed3588f9c81fb6180781ca687f305157cf3481f246d1a493fa348991d41a660b54e5db7ff5a4e4676570062b8c22b38b",
          "sha256": "caf51f3d51c5d95e931f411027688f1dde3986d5f2aad67ff1096ddddac36ac5",
          "sha1": "dea4b8e110b7b54a02a4907e32dbb0adee8a7168",
          "md5": "852be6055a31d2ce17b5d231b17f732e"
        }
      ]
    }
  ]
}
