{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter",
    "version": "3.2.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.2.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "3.2.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "version": {
            "requires": "3.2.5"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.6"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-3.2.5.jar",
          "url": "spring-boot-starter-3.2.5.jar",
          "size": 4768,
          "sha512": "6970acc921a992ba230b6e043a1b82a375757d710955f757bf8deb1e35adf4062e70ca7b77703b136cc8afdbabc073f0a419a6866603e1c43870f346394de72d",
          "sha256": "d4a2e024fa33697c9a2ccce6ca5fc3fe83d5e3822206932d5c7919948e227993",
          "sha1": "a9837a876129cc6fe5f3abf1de5ec0a16faaf003",
          "md5": "e08c02a0c5ba9611078c0f9f631527e3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.2.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "3.2.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "version": {
            "requires": "3.2.5"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.6"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-3.2.5.jar",
          "url": "spring-boot-starter-3.2.5.jar",
          "size": 4768,
          "sha512": "6970acc921a992ba230b6e043a1b82a375757d710955f757bf8deb1e35adf4062e70ca7b77703b136cc8afdbabc073f0a419a6866603e1c43870f346394de72d",
          "sha256": "d4a2e024fa33697c9a2ccce6ca5fc3fe83d5e3822206932d5c7919948e227993",
          "sha1": "a9837a876129cc6fe5f3abf1de5ec0a16faaf003",
          "md5": "e08c02a0c5ba9611078c0f9f631527e3"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-3.2.5.jar",
          "url": "spring-boot-starter-3.2.5.jar",
          "size": 4768,
          "sha512": "6970acc921a992ba230b6e043a1b82a375757d710955f757bf8deb1e35adf4062e70ca7b77703b136cc8afdbabc073f0a419a6866603e1c43870f346394de72d",
          "sha256": "d4a2e024fa33697c9a2ccce6ca5fc3fe83d5e3822206932d5c7919948e227993",
          "sha1": "a9837a876129cc6fe5f3abf1de5ec0a16faaf003",
          "md5": "e08c02a0c5ba9611078c0f9f631527e3"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-maven-optional",
          "version": "3.2.5"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-3.2.5.jar",
          "url": "spring-boot-starter-3.2.5.jar",
          "size": 4768,
          "sha512": "6970acc921a992ba230b6e043a1b82a375757d710955f757bf8deb1e35adf4062e70ca7b77703b136cc8afdbabc073f0a419a6866603e1c43870f346394de72d",
          "sha256": "d4a2e024fa33697c9a2ccce6ca5fc3fe83d5e3822206932d5c7919948e227993",
          "sha1": "a9837a876129cc6fe5f3abf1de5ec0a16faaf003",
          "md5": "e08c02a0c5ba9611078c0f9f631527e3"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-maven-optional",
          "version": "3.2.5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-3.2.5-javadoc.jar",
          "url": "spring-boot-starter-3.2.5-javadoc.jar",
          "size": 4735,
          "sha512": "a650678b828d706bd33f482669eb4ec58bdfa9406aaa6e8718633725b37a6cf2ff14937d59019c3a53b872dee23acaf5531ea6fae3d26d0ba6de3b130a835d28",
          "sha256": "87f47a425fa402deffa1c4a8d5e60864c87a51eff202a4473806154843d73b22",
          "sha1": "9cc9a100a87405e778699e0c6dff193262318144",
          "md5": "1493e533ac078d6d3a17fd41ff2f89d1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-3.2.5-sources.jar",
          "url": "spring-boot-starter-3.2.5-sources.jar",
          "size": 4734,
          "sha512": "cf170ce94a113d7458035d6087e6f12aa94c4ff218bb1fd9b19c9406b1a5675a139228646434206a2fc276a083d21a5b8a82072c5bafabfd91ebd875625aca84",
          "sha256": "e22e6beccee7abd1316b3a3a4aeaece49aa9dedd3be0de7bb9c8353cd3312fc6",
          "sha1": "ef9683d16ab6aa765cecffe728c569ea508a29d2",
          "md5": "ca91f1f2389d525fe6a2f3c7cb933a0f"
        }
      ]
    }
  ]
}
