{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-aspects",
    "version": "6.1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.aspectj",
          "module": "aspectjweaver",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "spring-aspects-6.1.6.jar",
          "url": "spring-aspects-6.1.6.jar",
          "size": 49660,
          "sha512": "7fd28d1e1bc6a08e8b474d2b90dda33b6a2ebf66ae276fe7ed8641d5f575e70983eb31919c369e8510899c3fba645c4f19f82787ac06dcaeef8c6d692a429c46",
          "sha256": "6e09aa06d26f0cffe214ff9c51baeed05ca4e7f655c0ea0a15b09c52c05df15f",
          "sha1": "409aba797564c23c08e2307f2df728aed117e914",
          "md5": "aaeb8e03738487d34f8126ab0b1d089a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.aspectj",
          "module": "aspectjweaver",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "spring-aspects-6.1.6.jar",
          "url": "spring-aspects-6.1.6.jar",
          "size": 49660,
          "sha512": "7fd28d1e1bc6a08e8b474d2b90dda33b6a2ebf66ae276fe7ed8641d5f575e70983eb31919c369e8510899c3fba645c4f19f82787ac06dcaeef8c6d692a429c46",
          "sha256": "6e09aa06d26f0cffe214ff9c51baeed05ca4e7f655c0ea0a15b09c52c05df15f",
          "sha1": "409aba797564c23c08e2307f2df728aed117e914",
          "md5": "aaeb8e03738487d34f8126ab0b1d089a"
        }
      ]
    }
  ]
}
