{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-test",
    "version": "3.2.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-test-3.2.5.jar",
          "url": "spring-boot-test-3.2.5.jar",
          "size": 245545,
          "sha512": "59129187a4acac6a92da8141ef7d98d891bedbed9c3ada9ee8e52d28527d58a6c4e85e5aa5245f5277f3a1e65db4d223a37dbd23e8632f8bea977ecee3b1d950",
          "sha256": "35a378e07aef678fe8a732837c84a3dfa8dcc06b7de87ca908247c0b7e23aa6f",
          "sha1": "df5c1f52e00aaa749932f9e213190b8635d59a86",
          "md5": "1281d5e4b03c923b00b813949a4d1914"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-test-3.2.5.jar",
          "url": "spring-boot-test-3.2.5.jar",
          "size": 245545,
          "sha512": "59129187a4acac6a92da8141ef7d98d891bedbed9c3ada9ee8e52d28527d58a6c4e85e5aa5245f5277f3a1e65db4d223a37dbd23e8632f8bea977ecee3b1d950",
          "sha256": "35a378e07aef678fe8a732837c84a3dfa8dcc06b7de87ca908247c0b7e23aa6f",
          "sha1": "df5c1f52e00aaa749932f9e213190b8635d59a86",
          "md5": "1281d5e4b03c923b00b813949a4d1914"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-test-3.2.5-javadoc.jar",
          "url": "spring-boot-test-3.2.5-javadoc.jar",
          "size": 414104,
          "sha512": "9d73481ec80ac59a76fb59bc64b5dd850e468b222d3a10ef4085b4d34ec6a71e2896ea09f77183e8962aa7fa9603ceeb7e542e711e121adde7587da6ec2ea8ec",
          "sha256": "42cab2004e2bb3f0414f931f796fc7974413c43c18af087fc5f754e063444fe3",
          "sha1": "0f3e2250e2f35620819d5df6c06e29ca2d99a333",
          "md5": "cdfb2426538ed7acc8ea26bb0fa02aef"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-test-3.2.5-sources.jar",
          "url": "spring-boot-test-3.2.5-sources.jar",
          "size": 168532,
          "sha512": "6bd38fa690abd511a36347507dd6e4ca8a11ee9128e40d7429db2951129f2bb329ef94a2e3861ac2257c3f38d69f96d387b9cd4d46989dace68a0fa362a98162",
          "sha256": "180147daa9e3a6ae35261010e239586906ad05623eb8fc1984c6be2f7155cc54",
          "sha1": "529e6a60f270436b49543a1daa5245cba4275e8a",
          "md5": "5ac091aca5c57863936d84c313206337"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-test-3.2.5.jar",
          "url": "spring-boot-test-3.2.5.jar",
          "size": 245545,
          "sha512": "59129187a4acac6a92da8141ef7d98d891bedbed9c3ada9ee8e52d28527d58a6c4e85e5aa5245f5277f3a1e65db4d223a37dbd23e8632f8bea977ecee3b1d950",
          "sha256": "35a378e07aef678fe8a732837c84a3dfa8dcc06b7de87ca908247c0b7e23aa6f",
          "sha1": "df5c1f52e00aaa749932f9e213190b8635d59a86",
          "md5": "1281d5e4b03c923b00b813949a4d1914"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-test-maven-optional",
          "version": "3.2.5"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-test-3.2.5.jar",
          "url": "spring-boot-test-3.2.5.jar",
          "size": 245545,
          "sha512": "59129187a4acac6a92da8141ef7d98d891bedbed9c3ada9ee8e52d28527d58a6c4e85e5aa5245f5277f3a1e65db4d223a37dbd23e8632f8bea977ecee3b1d950",
          "sha256": "35a378e07aef678fe8a732837c84a3dfa8dcc06b7de87ca908247c0b7e23aa6f",
          "sha1": "df5c1f52e00aaa749932f9e213190b8635d59a86",
          "md5": "1281d5e4b03c923b00b813949a4d1914"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-test-maven-optional",
          "version": "3.2.5"
        }
      ]
    }
  ]
}
