{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-tx",
    "version": "6.1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-tx-6.1.6.jar",
          "url": "spring-tx-6.1.6.jar",
          "size": 284954,
          "sha512": "5456bf6a0bada70a25bb477534749f39a27e607d7b55144908c076882da9dc9a8a05e95051675ef635b6a285a91e51860a14d3dba94db110ac3309a040fe5f85",
          "sha256": "dc76ab1629b986555fc83a0f83803aa591b91af46e9d187ac9eb999a99898b8f",
          "sha1": "4e18554fb6669f266108cc838a4619bbc8f7db8d",
          "md5": "290de6a7f55216181b65e1f682fd9bc4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-tx-6.1.6.jar",
          "url": "spring-tx-6.1.6.jar",
          "size": 284954,
          "sha512": "5456bf6a0bada70a25bb477534749f39a27e607d7b55144908c076882da9dc9a8a05e95051675ef635b6a285a91e51860a14d3dba94db110ac3309a040fe5f85",
          "sha256": "dc76ab1629b986555fc83a0f83803aa591b91af46e9d187ac9eb999a99898b8f",
          "sha1": "4e18554fb6669f266108cc838a4619bbc8f7db8d",
          "md5": "290de6a7f55216181b65e1f682fd9bc4"
        }
      ]
    }
  ]
}
