{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-expression",
    "version": "6.1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-expression-6.1.6.jar",
          "url": "spring-expression-6.1.6.jar",
          "size": 302983,
          "sha512": "96c4712e5673fb30c55aea7cc7a5d29027780f71b7c0db8d539d95ff7a371cbe16013f59dda4163f5ceda2d09897b5486871cdb3bb22d11fa4858aad0c5aa8b2",
          "sha256": "6e53929ab7abda1a43b7d81cefcc441d187eb41aab493d2f61cc6161512c2d97",
          "sha1": "9c3d7f0e17a919a4ea9f087e4e2140ad39776bc8",
          "md5": "80acfe831814a3712ae046de5baa2fe9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-expression-6.1.6.jar",
          "url": "spring-expression-6.1.6.jar",
          "size": 302983,
          "sha512": "96c4712e5673fb30c55aea7cc7a5d29027780f71b7c0db8d539d95ff7a371cbe16013f59dda4163f5ceda2d09897b5486871cdb3bb22d11fa4858aad0c5aa8b2",
          "sha256": "6e53929ab7abda1a43b7d81cefcc441d187eb41aab493d2f61cc6161512c2d97",
          "sha1": "9c3d7f0e17a919a4ea9f087e4e2140ad39776bc8",
          "md5": "80acfe831814a3712ae046de5baa2fe9"
        }
      ]
    }
  ]
}
