{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-aop",
    "version": "3.2.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.2.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.1.6"
          }
        },
        {
          "group": "org.aspectj",
          "module": "aspectjweaver",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-aop-3.2.5.jar",
          "url": "spring-boot-starter-aop-3.2.5.jar",
          "size": 4769,
          "sha512": "a55cf4d37719eecd0e4e0b4ed11c9fe479b68ae33bfb4a6d7c1b91a2a42674c59d54ac805ca9d3c47afa27545c6dddddd9cc1f0c6b04092eb71f7ccffdb49660",
          "sha256": "b0ae15a5d1d7c39918d29925cfc47fcfda6d61afe863b9db401d31b4d5f13fc5",
          "sha1": "1c6c5d81e6c7f8b3e255c9e384153e9f52a93d1b",
          "md5": "ae58c3c0a5c089e905da41f8d56769bc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.2.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.1.6"
          }
        },
        {
          "group": "org.aspectj",
          "module": "aspectjweaver",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-aop-3.2.5.jar",
          "url": "spring-boot-starter-aop-3.2.5.jar",
          "size": 4769,
          "sha512": "a55cf4d37719eecd0e4e0b4ed11c9fe479b68ae33bfb4a6d7c1b91a2a42674c59d54ac805ca9d3c47afa27545c6dddddd9cc1f0c6b04092eb71f7ccffdb49660",
          "sha256": "b0ae15a5d1d7c39918d29925cfc47fcfda6d61afe863b9db401d31b4d5f13fc5",
          "sha1": "1c6c5d81e6c7f8b3e255c9e384153e9f52a93d1b",
          "md5": "ae58c3c0a5c089e905da41f8d56769bc"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-aop-3.2.5.jar",
          "url": "spring-boot-starter-aop-3.2.5.jar",
          "size": 4769,
          "sha512": "a55cf4d37719eecd0e4e0b4ed11c9fe479b68ae33bfb4a6d7c1b91a2a42674c59d54ac805ca9d3c47afa27545c6dddddd9cc1f0c6b04092eb71f7ccffdb49660",
          "sha256": "b0ae15a5d1d7c39918d29925cfc47fcfda6d61afe863b9db401d31b4d5f13fc5",
          "sha1": "1c6c5d81e6c7f8b3e255c9e384153e9f52a93d1b",
          "md5": "ae58c3c0a5c089e905da41f8d56769bc"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-aop-maven-optional",
          "version": "3.2.5"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-aop-3.2.5.jar",
          "url": "spring-boot-starter-aop-3.2.5.jar",
          "size": 4769,
          "sha512": "a55cf4d37719eecd0e4e0b4ed11c9fe479b68ae33bfb4a6d7c1b91a2a42674c59d54ac805ca9d3c47afa27545c6dddddd9cc1f0c6b04092eb71f7ccffdb49660",
          "sha256": "b0ae15a5d1d7c39918d29925cfc47fcfda6d61afe863b9db401d31b4d5f13fc5",
          "sha1": "1c6c5d81e6c7f8b3e255c9e384153e9f52a93d1b",
          "md5": "ae58c3c0a5c089e905da41f8d56769bc"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-aop-maven-optional",
          "version": "3.2.5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-aop-3.2.5-javadoc.jar",
          "url": "spring-boot-starter-aop-3.2.5-javadoc.jar",
          "size": 4741,
          "sha512": "c7684b7da65a3340cba180a46c9cd97822ec89a2106e84d5888762e0a05f2470ea7f381f4c044a6e18c69344b9bdaefa0e6175bad6e8cddedab9b1172bd95cd2",
          "sha256": "e03d2f474a54d79c76cacc1d015c1b46d61bfb4d1c90d696cd053530840854ed",
          "sha1": "4f03a91f8660d4fecefd19fdee785628a4d929b5",
          "md5": "f0b9feb46cb11ee1c91a56d1de918e6a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-aop-3.2.5-sources.jar",
          "url": "spring-boot-starter-aop-3.2.5-sources.jar",
          "size": 4740,
          "sha512": "d4eb0fe396ad8514dec6746bdc8a69d2be5ed2c154e966b6fc3e34ac3b7fbd62147a8e8c41e75b1ff824daf512f5284f2676773865523854e74a9caab88b71b1",
          "sha256": "1d03a3afcbbb35f5cfd90631c9bbe6a2de6de088ce7c127fd6193303376425fe",
          "sha1": "7e81c78371828738705aca7a20c1e60d965f10f1",
          "md5": "415c879c0edfd46565fe384e18752d40"
        }
      ]
    }
  ]
}
