{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot",
    "version": "3.2.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-3.2.5.jar",
          "url": "spring-boot-3.2.5.jar",
          "size": 1614716,
          "sha512": "2e11a5d796ff7cedc0460def9839f1b49e4d938d1cd974652f193cb425b5e5cd96dbfcb86af705ed181c64f815eb96bbf1562bb5deb99de5ec8ed6f6d740f0c7",
          "sha256": "f0149646b350f16911b4525e0c2031abfd43da4b21ebedfe0d94e53aa21f9a7e",
          "sha1": "eec72431f6f56a50c9919129665ba3359ca02104",
          "md5": "9a3d5b3f100ab90a090baa2d15bc21f7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-3.2.5.jar",
          "url": "spring-boot-3.2.5.jar",
          "size": 1614716,
          "sha512": "2e11a5d796ff7cedc0460def9839f1b49e4d938d1cd974652f193cb425b5e5cd96dbfcb86af705ed181c64f815eb96bbf1562bb5deb99de5ec8ed6f6d740f0c7",
          "sha256": "f0149646b350f16911b4525e0c2031abfd43da4b21ebedfe0d94e53aa21f9a7e",
          "sha1": "eec72431f6f56a50c9919129665ba3359ca02104",
          "md5": "9a3d5b3f100ab90a090baa2d15bc21f7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-3.2.5-javadoc.jar",
          "url": "spring-boot-3.2.5-javadoc.jar",
          "size": 2327650,
          "sha512": "5ad46a6551c629d72d7ce5402f046fe028b7f942e06cc2216ed27d18b2ab5cfd8c340c252c0d2dd5bb3514c95350ff259ee3ae61c1ea4cd1c2bc23771149a54d",
          "sha256": "2d720c79d8bb02752cea9d8b5beadbc4733350b314fdcecd886cd0463b6960ce",
          "sha1": "08478d6349d77fac0b8a9b91885ab93d88efd3ed",
          "md5": "56e2628ea53306432d24fd6fdce1c1ab"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-3.2.5-sources.jar",
          "url": "spring-boot-3.2.5-sources.jar",
          "size": 1111303,
          "sha512": "8a17c83dc0ece7fd3c4f21facd059d5bf449b782ad441fc0918b4973df2f4436c49472e1eba1abbf1597a6ad7ac033c7bb65875de1731e55fb00e8019354f01e",
          "sha256": "abe5fe7115f549e236feaa25d8eda19dcec05954635be87aa1310dbe14ae1fd0",
          "sha1": "b3dbf02fd1e0cf8b1b7c6f6d489adaea7612a891",
          "md5": "4aec10390a3b6b204842d741a3c7931c"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-3.2.5.jar",
          "url": "spring-boot-3.2.5.jar",
          "size": 1614716,
          "sha512": "2e11a5d796ff7cedc0460def9839f1b49e4d938d1cd974652f193cb425b5e5cd96dbfcb86af705ed181c64f815eb96bbf1562bb5deb99de5ec8ed6f6d740f0c7",
          "sha256": "f0149646b350f16911b4525e0c2031abfd43da4b21ebedfe0d94e53aa21f9a7e",
          "sha1": "eec72431f6f56a50c9919129665ba3359ca02104",
          "md5": "9a3d5b3f100ab90a090baa2d15bc21f7"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-maven-optional",
          "version": "3.2.5"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-3.2.5.jar",
          "url": "spring-boot-3.2.5.jar",
          "size": 1614716,
          "sha512": "2e11a5d796ff7cedc0460def9839f1b49e4d938d1cd974652f193cb425b5e5cd96dbfcb86af705ed181c64f815eb96bbf1562bb5deb99de5ec8ed6f6d740f0c7",
          "sha256": "f0149646b350f16911b4525e0c2031abfd43da4b21ebedfe0d94e53aa21f9a7e",
          "sha1": "eec72431f6f56a50c9919129665ba3359ca02104",
          "md5": "9a3d5b3f100ab90a090baa2d15bc21f7"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-maven-optional",
          "version": "3.2.5"
        }
      ]
    }
  ]
}
