{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-jdbc",
    "version": "6.1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "6.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-jdbc-6.1.6.jar",
          "url": "spring-jdbc-6.1.6.jar",
          "size": 467338,
          "sha512": "3c513ec606ab67e69c1bb4b49b07a31c41cda60a064b0b83e30f0b2cb40ee10ade84f8e18f2c37d8c10d45a5fa4c0054d827219ad3aa0efb2f158d32928c3d4b",
          "sha256": "4f575ff3515214853590f07ccbdac48947a4bd1246596017fb048ab77d0290ae",
          "sha1": "3f8a440a49c15264ff438598b715bd00c5a88109",
          "md5": "c8c19b4161ee251c20a0b6eba94ed825"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "6.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-jdbc-6.1.6.jar",
          "url": "spring-jdbc-6.1.6.jar",
          "size": 467338,
          "sha512": "3c513ec606ab67e69c1bb4b49b07a31c41cda60a064b0b83e30f0b2cb40ee10ade84f8e18f2c37d8c10d45a5fa4c0054d827219ad3aa0efb2f158d32928c3d4b",
          "sha256": "4f575ff3515214853590f07ccbdac48947a4bd1246596017fb048ab77d0290ae",
          "sha1": "3f8a440a49c15264ff438598b715bd00c5a88109",
          "md5": "c8c19b4161ee251c20a0b6eba94ed825"
        }
      ]
    }
  ]
}
